### ISSUE TITLE
An error occurred when using some old mods

### ISSUE THREAD

**Issue by Sabermoon** [IllusionMods/ModBoneImplantor#2]
I installed HF 3.9 and found that an error occurred when loading a card, the error is as follows:
```
[Error  :Null Checks] Swallowing exception to prevent game crash!
System.ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
at System.Collections.Generic.List`1<DynamicBone/Particle>.get_Item (int) <0x00083>
at (wrapper dynamic-method) DynamicBone.DMD<DynamicBone..ResetParticlesPosition> (DynamicBone) <0x00150>

[Error  :Null Checks] Swallowing exception to prevent game crash!
System.ArgumentOutOfRangeException: Argument is out of range.
Parameter name: index
at System.Collections.Generic.List`1<DynamicBone/Particle>.get_Item (int) <0x00083>
at (wrapper dynamic-method) DynamicBone.DMD<DynamicBone..ResetParticlesPosition> (DynamicBone) <0x00150>
```

I spent several hours to determine the problem, and here are my conclusions:
After using the glove parts provided by [JM] keqing.zipmod, this error occurs when the display mode is switched from naked to clothing, and it does not appear in the previous HF 3.8. I confirm that it is related to ModBoneImplantor 1.0, but cannot continue to test more.

**Comment by ManlyMarco** [comment]
Does this have any effect on the game other than this message?

**Comment by Sabermoon** [comment]
> Does this have any effect on the game other than this message?

As far as I saw, although an error occurred, the display switching can be completed. I don’t know if there is any other effect.

**Comment by ManlyMarco** [comment]
Looks like this is harmless and has no effect other than the log message. It can't be easily fixed, so I'm closing this issue as wontfix.
