### ISSUE TITLE
README.MD and MB Update Proposal

### ISSUE THREAD

**Issue by Jaws-git** [IllusionMods/ModBoneImplantor#4]
1. The two parameters of the BoneImplant script for KoikatsuModdingTools should be covered in the readme in order to avoid ambiguity.
this part could be added after point 2:
```
- fill in the two parameters Trf Src and Trf Dst as follows
     - Trf Src: the first custom bone in the chain to be added to the game
     - Trf Dst: an existing (vanilla) game bone that is the parent to the Src bone
```

2. Going even further, similar descriptions could be added as tooltips to the MB itself, showing up when hovering the mouse over either one

3. Last, and this is more of a personal preference, I propose the labeling of the parameters to be switched around
**Src** would be the existing parent bone, the "source" of the transform data for the custom bone(s).
**Dst** would be the newly added custom bone, the "destination" to apply the transform to and target of the bone implant process.

**Comment by ManlyMarco** [comment]
> 3\. Last, and this is more of a personal preference, I propose the labeling of the parameters to be switched around
>     **Src** would be the existing parent bone, the "source" of the transform data for the custom bone(s).
>     **Dst** would be the newly added custom bone, the "destination" to apply the transform to and target of the bone implant process.

This is not possible without breaking backwards compatibility.
